app = "zorservbot"
primary_region = "mad"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Копируем все файлы включая папки
[build]
  builtin = "dockerfile"
