app = "zorservbot"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true
 [checks]
  [checks.alive]
    type = "tcp"
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"
    port = 22

