app = "zorservbot"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true

[checks]
  [checks.alive]
    type = "process"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
